// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQeR06Qd0w42SzzAEO1EFWoukVBGNLSA',
    appId: '1:186082612658:web:6a3561b47bf45026fc80ab',
    messagingSenderId: '186082612658',
    projectId: 'pokenion',
    authDomain: 'pokenion.firebaseapp.com',
    storageBucket: 'pokenion.firebasestorage.app',
    measurementId: 'G-5YXY3RES14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrrBYKknIqdAIyt2JdXE8O0hWUrynPbE',
    appId: '1:186082612658:android:1d4b13e42c29f5a1fc80ab',
    messagingSenderId: '186082612658',
    projectId: 'pokenion',
    storageBucket: 'pokenion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--h51giJ6GGJFKclseMBcZ-4muxLp8_M',
    appId: '1:186082612658:ios:5daeff7236356822fc80ab',
    messagingSenderId: '186082612658',
    projectId: 'pokenion',
    storageBucket: 'pokenion.firebasestorage.app',
    iosClientId: '186082612658-f93q0ts2juvk429tvcoof1hft784uhge.apps.googleusercontent.com',
    iosBundleId: 'com.erohf.pokenion',
  );
}
